### ISSUE TITLE
Tydeliggjøre oppgave (nåværende) 1

### ISSUE THREAD

**Issue by terjesyl** [terjesyl/sikt-workshop#6]
delvis løst av #22 

Legg til forventningsavklaring på oppgave 1, at man ikke skal trenge lang tid på hver oppgave.

Bedre beskrive hva man skal gjøre. Kan overtenkes nå og kan føre til misforståelse om hva som skal gjøres.
- FIktiv info eller reell info
- Er alle obligatoriske felter tilstede allerede?
- Hva skal fylles ut/byttes ut?

**Comment by terjesyl** [comment]
Kan for eksempel bruke fiktive URL-er til https://example.org i oppgavesvarene

**Comment by KjerstiSteien** [comment]
Få inn et scenario som setter oppgaven i kontekst, som vi har på oppgave 2.
