### ISSUE TITLE
Beskrive tilgjengelige ressurser og verktøy

### ISSUE THREAD

**Issue by KjerstiSteien** [terjesyl/sikt-workshop#7]
Beskrive verktøy og hva vi har for å bistå de som skal beskrive datasett.
Python-bibliotek osv.

**Comment by terjesyl** [comment]
- [x] `datacatalogtordf` Python-bibliotek
- [x] Validatoren vår
- [x] Den andre Turtle-validatoren/editoren: https://www.easyrdf.org/converter
- [x] Spec'en (DCAT, DCAT-AP)
- [x] SHACL for validering
- [x] SPARQL for spørringer
- [x] ~Visualisering (?)~ kjenner ikke til noen gode og stabile verktøy for dette.
- [x] Nevne de andre spec'ene og katalogene, og lenke til side som forklarer sammenhengen.

**Comment by terjesyl** [comment]
Løst av #30
